MVCOrderManagmentUi/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCOrderManagmentUi.Data;
using MVCOrderManagmentUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCOrderManagmentUi.Controllers
{
    public class DashboardController : Controller
    {
        private readonly GSparkShopDBContext _context;
        private DashboardDTO DTO;
        public DashboardController(GSparkShopDBContext context)
        {
            _context = context;
        }
        public IActionResult ShowDashboard()
        {
            DTO = new DashboardDTO
            {
                ActiveCarts = _context.ShoppingCarts.Count(),
                ItemsInCarts = _context.ShoppingCartContents.Count(),
                PotentialSales = _context.ShoppingCartContents.Include(x => x.Prod).Sum(x => x.Prod.ProdPrice),
                ShoppingCarts = new List<ShoppingCart>()
            };

            var result = _context.ShoppingCartContents.Include(x => x.ShoppingCart).Include(x => x.Prod).ToList();
            DTO.ShoppingCarts = from cart in result
                              group cart by cart.ShoppingCartId;
            var queryResult = _context.ShoppingCartContents.Include(x => x.Prod);
            DTO.MostAddedItemToCart = (from prods in queryResult.AsEnumerable()
                                       group prods by prods.Prod.ProdName).Take(1);
            return View(DTO);
        }
        public IActionResult ShowAllShoppingCarts()
        {
            return View();
        }
    }
}

MVCOrderManagmentUi/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCOrderManagmentUi.Data;
using MVCOrderManagmentUi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCOrderManagmentUi.Controllers
{
    public class ProductController : Controller
    {
        private readonly GSparkShopDBContext _context;
        public ProductController(GSparkShopDBContext context)
        {
            _context = context;
        }
        [Authorize]
        public IActionResult ViewProducts(string filterby, bool? des)
        {
            List<Product> Results = new List<Product>();
            switch (filterby)
            {
                case "none":
                    Results = _context.Products.ToList();
                    break;
                case "prodname":
                    if (des == true)
                    {
                        Results = _context.Products.OrderByDescending(x => x.ProdName).ToList();
                        break;
                    }
                    else 
                    {
                        Results = _context.Products.OrderBy(x => x.ProdName).ToList();
                        break;
                    }  
                case "prodprice":
                    if (des == true)
                    {
                        Results = _context.Products.OrderByDescending(x => x.ProdPrice).ToList();
                        break;
                    }
                    else
                    {
                        Results = _context.Products.OrderBy(x => x.ProdPrice).ToList();
                        break;
                    }
                case "prodtype":
                    if (des == true)
                    {
                        Results = _context.Products.OrderByDescending(x => x.ProdType).ToList();
                        break;
                    }
                    else
                    {
                        Results = _context.Products.OrderBy(x => x.ProdType).ToList();
                        break;
                    }
                default:
                    Results = _context.Products.ToList();
                    break;
            }
            return View(Results);
        }
        [HttpGet]
        [Authorize]
        public IActionResult AddNewProduct()
        {
            CreateProductDto NewProductDetails = new CreateProductDto();
            NewProductDetails.ProductType = _context.Products.Select(x => x.ProdType).Distinct().ToList();
            return View(NewProductDetails);
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddNewProduct(CreateProductDto createProductDto)
        {
            _context.Products.Add(new Product
            {
                ProdName = createProductDto.Product.ProdName,
                ProdPrice = createProductDto.Product.ProdPrice,
                ProdType = createProductDto.Product.ProdType
            });
            _context.SaveChanges();
            return RedirectToAction("ViewProducts",routeValues: new {filterby = "none"});
        }
        public IActionResult DeleteProduct(int? prodId, bool? forceDelete)
        {
            if (forceDelete == true)
            {
                _context.ShoppingCartContents.RemoveRange(_context.ShoppingCartContents.Where(x=>x.ProdId == prodId));
                var productToBeDeleted = _context.Products.FirstOrDefault(x => x.ProdId == prodId);
                _context.Products.Remove(productToBeDeleted);
                _context.SaveChanges();
            }
            else
            {
                var productToBeDeleted = _context.Products.FirstOrDefault(x => x.ProdId == prodId);
                _context.Products.Remove(productToBeDeleted);
                _context.SaveChanges();
            }
            return RedirectToAction("ViewProducts", routeValues: new { filterby = "none" });
        }

        [HttpGet]
        public IActionResult GetDeleteModal(int? prodId)
        {
            if (_context.ShoppingCartContents.Any(x=>x.ProdId == prodId))
            {
                return PartialView("_DeleteModal", _context.Products.FirstOrDefault(x=>x.ProdId == prodId));
            }
            return RedirectToAction("DeleteProduct", routeValues: new { prodId = prodId, forceDelete = "true"});
        }
        [HttpGet]
        public IActionResult ViewDetails(int? prodId)
        {
            var product = _context.Products.FirstOrDefault(x=>x.ProdId == prodId);
            return PartialView("_ViewDetails", product);
        }
        [HttpGet]
        public IActionResult EditDetails(int? prodId)
        {
            var product = _context.Products.FirstOrDefault(x => x.ProdId == prodId);
            return PartialView("_EditProduct", product);
        }
        [HttpPost]
        public IActionResult EditDetails(Product editedProduct)
        {
          
            _context.Products.Update(editedProduct);
            _context.SaveChanges();
            return RedirectToAction("ViewProducts", routeValues: new { filterby = "none" });
        }
    }
}

MVCOrderManagmentUi/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Solana</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/WelcomeStyles.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/css/DashboardStyles.css"/>
    <link href="~/css/ProductStyles.css" rel="stylesheet"/>
    <link href="~/css/LoginFormStyles.css" rel="stylesheet"/>
    <link href="~/css/RegistrationFormStyles.css" rel="stylesheet" />
    <link href="~/css/AboutStyles.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Solana - Ecomm Solution</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="ShowDashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ViewProducts" asp-route-filterby="none">Products</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" >
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 content">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC Order Management Ui - <a asp-page="/About">About Us</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/c1bd62e8b3.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>